AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Exclude:
    - 'lib/**/*'

Metrics/AbcSize:
  Exclude:
    - 'lib/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/**/*'

Metrics/MethodLength:
  Exclude:
    - 'lib/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/**/*'
